openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:3000/api
info:
  description: This is a simple API
  version: "1.0.0"
  title: Warehouse management system API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: products
    description: All products
  - name: suppliers
    description: Operations of users staff
paths:
  /products:
    get:
      tags:
        - products
      summary: Lấy một danh sách các sản phẩm
      description: |
        Search by passing in the appropriate parameters
      parameters:
        - in: query
          name: name
          description: truyền một xâu ký tự để tìm kiếm sản phẩm 
          schema:
            type: string
        - in: query
          name: color
          description: màu của sản phẩm
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: size
          description: kích cỡ của sản phẩm
          schema:
            type: string
        - in: query
          name: cat
          description: thể loại
          schema:
            type: string
      responses:
        '200':
          description: kết quả ứng với tiêu chuẩn tìm kiếm
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: bad input parameter
    post:
      tags:
        - products
      summary: Thêm sản phẩm
      description: Thêm một sản phẩm vào trong hệ thống
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: sản phẩm được tạo thành công
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
  /products/{product_id}:
    get:
      tags:
        - products
      summary: Lấy sản phẩm với mã id tương ứng
      parameters:
        - in: path
          name: product_id
          description: Id của sản phẩm
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /suppliers:
    post:
      tags:
        - suppliers
      summary: Thêm nhà cung cấp mới
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Meta Inc'
                address:
                  type: string
                  example: 'Ha Noi, Viet Nam'
                cperson:
                  type: string
                  example: 'Mark Zuckerberg'
                cperson_phone:
                  type: string
                  example: '2092014567'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
  /suppliers/{supplier_id}:
    put:
      tags:
        - suppliers
      summary: Update thong tin nhà cung cấp
      parameters:
        - in: path
          name: supplier_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
    delete:
      tags:
        - suppliers
      summary: Xóa nhà cung cấp
      parameters:
        - in: path
          name: supplier_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
  /images:
    post:
      tags:
        - images
      summary: Upload ảnh
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Image'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /images/{image_id}:
    get:
      tags:
        - images
      summary: Lấy một ảnh với id tương ứng
      parameters:
        - in: path
          name: image_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  img:
                    type: string
                    format: base64
  /stock:
    post:
      tags:
        - stock
      summary: Nhập thêm sản phẩm mới (chưa có)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: string
                  example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
                quantity:
                  type: integer
                  example: 2
                size:
                  type: string
                  example: 'XL'
                color:
                  type: string
                  example: 'black'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
        '500':
          description:  Internal Server Error
  /stock/{stock_id}:
      put:
        tags:
          - stock
        summary: Nhập thêm/Xóa bớt sản phẩm đã có 
        parameters:
          - in: path
            name: stock_id
            required: true
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Stock'
components:
  schemas:
    Supplier:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: b340f1ee-6cd4-4b01-90e6-d701748f0851
        name:
          type: string
          example: 'Meta Inc'
        address:
          type: string
          example: 'Ha Noi, Viet Nam'
        cperson:
          type: string
          example: 'Mark Zuckerberg'
        cperson_phone:
          type: string
          example: '2092014567'
        status:
          type: string
          enum: ['active', 'inactive']
          default: 'active'
    Product:
      type: object
      required:
        - id
        - supplierId
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Tee basic ss1 CREWZ áo thun tay lỡ unisex Local Brand - AO_THUN_DVR
        description:
          type: string
          example: 
        idImages:
          type: array
          items:
            type: string
        status:
          type: string
          enum: ['active', 'inactive']
          default: 'active'
    Image:
      type: object
      required:
        - id
        - img_buffer
        - img_type
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        img_buffer:
          type: object
        img_type:
          type: string
          enum: ['png', 'jpeg', 'jpg', 'webp']
    Stock:
      type: object
      required:
        - product_id
      properties:
        product_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        quantity:
          type: integer
        color:
          type: string
        size:
          type: string