@hostname = http://localhost:5000/api

POST   http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "123",
    "email": "123",
    "password": "ky123"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}

###
GET http://localhost:5000/api/auth/checklogin HTTP/1.1

###
GET http://localhost:5000/api/auth/logout HTTP/1.1


###
PUT  http://localhost:5000/api/users/62366f863bfae264f7c50fdf HTTP/1.1
Content-Type: application/json

{
    "userId": "62366f863bfae264f7c50fdf",
    "username": "123",
    "password": "gitnew"
}

###
GET   http://localhost:5000/api/users/62366f863bfae264f7c50fdf HTTP/1.1
Content-Type: application/json


# upload file img
###
POST http://localhost:5000/api/upload HTTP/1.1
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< 1.png

###
POST http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

{
    "title": "test2", 
    "desc": "test1",
    "username": "test1"
}

###
PUT http://localhost:5000/api/posts/6236dd2cbc2bbf3948508c47 HTTP/1.1
Content-Type: application/json

{
    "title": "test2", 
    "desc": "test2",
    "username": "test1"
}



###
GET  http://localhost:5000/api/posts HTTP/1.1

###
DELETE  http://localhost:5000/api/posts/6236e2bdf170486c8683c7e0 HTTP/1.1
Content-Type: application/json

{
    "username": "test1"
}

//Update delete post of user
###
PUT http://localhost:5000/api/authorPost?user=123 HTTP/1.1
Content-Type: application/json

{
    "username": "123",
    "newUsername": "test2"
}

###
DELETE  http://localhost:5000/api/authorPost?user=test2 HTTP/1.1
Content-Type: application/json

{
    "username": "test2"
}

# Categories
###
POST http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json

{
    "name":"Cinema"
}

###
GET  http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json

###
PUT  http://localhost:5000/api/categories HTTP/1.1
Content-Type: application/json

{
    "_id": "623735771973d407e78ec708",
    "name":"Life"
}

### Thao tác với products 
### 
GET http://localhost:5000/api/products/ HTTP/1.1
Content-Type: application/json

{

}