@BASE_URL=http://localhost:5000/api
@ID=63848b1fa175d658021e89d9
@ID2=638479407de2640868f89da4

### With supplier

### Get all
GET {{BASE_URL}}/suppliers HTTP/1.1

### Get by id
GET {{BASE_URL}}/suppliers/{{ID}} HTTP/1.1

### Create
POST {{BASE_URL}}/suppliers HTTP/1.1
Content-Type: application/json

{
    "name": "Meta Inc",
    "address": "Ha Noi Viet Nam",
    "cperson": "Mark Zuckerberg",
    "cperson_phone": "2092014567"
}

### Update
PUT {{BASE_URL}}/suppliers/{{ID}} HTTP/1.1
Content-Type: application/json

{
    "name": "Meta Inc",
    "address": "Ha Noi, Viet Nam"
}

### Delete
DELETE {{BASE_URL}}/suppliers/{{ID}} HTTP/1.1

### End supplier

### With Stock

### Add more stock
GET {{BASE_URL}}/stock HTTP/1.1
Content-Type: application/json

{
    "product_id": "63848b1fa175d658021e89d9",
    "quantity": "12",
    "zize": "XXL",
    "color": "34568B"
}